Make Unix sockets writable for user group
mopidy/mopidy-mpd pull request #56
Opened 2022-08-08 19:30 UTC by very-amused

When Mopidy is run as a system service under the `mopidy` user, Unix sockets are currently created with a umask of `022`, which makes other users unable to connect due to having no write permission. This PR ensures Unix sockets are created with a umask of `002`, making them writable to users in the `mopidy` group and thus usable to users added to this group.

2022-08-14 00:58 UTC, djmattyg007 requested changes
Should we add a feature flag for this?

2022-08-14 00:58 UTC, djmattyg007 commented on mopidy_mpd/network.py
> +            os.umask(oldmask)
The call to `sock.bind()` should be wrapped in a try/finally clause, with the second umask call being placed in the `finally` block.

2022-08-18 06:06 UTC, very-amused commented
The try/finally clause that was requested has been added. I don't see the need for a feature flag to enable this behavior, I believe making sockets group-writable is a sane default.

2022-08-19 02:21 UTC, djmattyg007 commented
> I don't see the need for a feature flag to enable this behavior, I believe making sockets group-writable is a sane default.

While I agree with you, this code removes the ability of users to control the umask themselves for this socket, so it's worth thinking about.

2022-10-16 13:45 UTC, very-amused commented
Apologies for the lack of updates for a while. I just implemented the config option `mpd/socket_permissions` with a default value of `775`. The behavior of making Unix sockets group-writable by default is retained, while allowing users to control the umask themselves if desired.

2025-01-03 16:30 UTC, closed without merging